"""The Analysis Brief: a written client deliverable, generated not typed.

Deterministic side only. ``build_brief_facts`` extends the narrative fact
sheet with the monthly-actuals block and the vs-budget unit-cost comparison;
``render_brief_html`` typesets the phrased sections into a self-contained,
print-styled, script-free HTML document in Lumnia's design language. The
AI call itself lives in ``narrative.generate_brief`` — Claude phrases the
five fixed sections from these facts and never computes a figure.
"""
from __future__ import annotations

import datetime as _dt
import html as _html
from typing import Any, Dict, List, Optional

from . import narrative

# fixed section keys, in reading order — mirrors the reference work sample
SECTION_KEYS = ("engagement", "cash", "unit_cost", "trajectory", "delivers")

SECTION_TITLES = {
    "en": {"engagement": "The engagement in brief",
           "cash": "Where the money went",
           "unit_cost": "The cost to produce a tonne",
           "trajectory": "The path to profit",
           "delivers": "What the system delivers"},
    "fr": {"engagement": "La mission en bref",
           "cash": "Où est allé l'argent",
           "unit_cost": "Le coût de production par tonne",
           "trajectory": "Le chemin vers la rentabilité",
           "delivers": "Ce que le système apporte"},
}

_STR = {
    "en": {"kicker": "Analysis brief", "audited": "every figure computed",
           "footer": ("Generated by Lumnia from the audited workbook — every "
                      "figure on this page traces to deterministic "
                      "computation over the uploaded data."),
           "audit_line": lambda ok, bad, un: (
               f"Audit: {ok} relation(s) verified · {bad} flagged · "
               f"{un} unverified"),
           "target": "budget target", "actual": "latest actual",
           "margin": "operating margin", "period": "period"},
    "fr": {"kicker": "Brief d'analyse", "audited": "chaque chiffre calculé",
           "footer": ("Généré par Lumnia à partir du classeur audité — chaque "
                      "chiffre de cette page provient d'un calcul "
                      "déterministe sur les données déposées."),
           "audit_line": lambda ok, bad, un: (
               f"Audit : {ok} relation(s) vérifiée(s) · {bad} signalée(s) · "
               f"{un} non vérifiée(s)"),
           "target": "cible budget", "actual": "dernier réel",
           "margin": "marge d'exploitation", "period": "période"},
}


def build_brief_facts(report: Dict[str, Any],
                      audit: Optional[Dict[str, Any]] = None) -> str:
    """The narrative fact sheet plus the monthly block — the brief's spine is
    the actual-vs-budget story, so those figures must be in front of the
    model verbatim."""
    lines: List[str] = [narrative.build_facts(report, audit)]
    model = report.get("model") or {}
    mo = model.get("monthly")
    if mo:
        periods = [str(p)[:7] for p in mo.get("periods") or []]
        lines.append(f"MONTHLY ACTUALS ({len(periods)} months: "
                     f"{periods[0] if periods else '?'}.."
                     f"{periods[-1] if periods else '?'})")
        for role, m in (mo.get("metrics") or {}).items():
            lines.append("MONTHLY " + narrative._series_line(role, m, periods))
        for name, vals in (mo.get("derived") or {}).items():
            lines.append("MONTHLY " + narrative._series_line(
                f"derived {name}", {"label": name, "values": vals}, periods))
        ucb = mo.get("unit_cost_budget")
        if ucb:
            var = ", ".join(f"{p}={v}%" for p, v in
                            zip(periods, ucb["variance_pct"]) if v is not None)
            lines.append(
                f"MONTHLY ACTUAL unit cost vs BUDGET ({ucb['basis']}): "
                f"target={narrative._fmt(ucb['target'])} for "
                f"{ucb['target_period']}; variance by month: {var}")
    return "\n".join(lines)


def _stat_tiles(report: Dict[str, Any], lang: str) -> List[tuple]:
    """The deterministic stat strip under the title — straight from the
    model, never from the phrased text."""
    s = _STR[lang]
    model = report.get("model") or {}
    tiles: List[tuple] = []
    mo = model.get("monthly") or {}
    ucb = mo.get("unit_cost_budget")
    if ucb:
        actual = (mo.get("derived") or {}).get(ucb["basis"]) or []
        last = next((v for v in reversed(actual) if v is not None), None)
        if last is not None:
            tiles.append((s["actual"], narrative._fmt(round(last, 2))))
        tiles.append((f"{s['target']} ({ucb['target_period']})",
                      narrative._fmt(ucb["target"])))
    margin = (model.get("derived") or {}).get("margin_pct") or []
    lastm = next((v for v in reversed(margin) if v is not None), None)
    if lastm is not None:
        tiles.append((s["margin"], f"{round(lastm)}%"))
    periods = model.get("periods") or []
    if periods:
        tiles.append((s["period"], f"{periods[0]}–{periods[-1]}"))
    return tiles[:4]


def render_brief_html(report: Dict[str, Any], phrased: Dict[str, Any],
                      audit: Optional[Dict[str, Any]], client_name: str,
                      lang: str = "en") -> str:
    """Typeset the brief: pure HTML+CSS, no scripts, prints to two clean
    pages. Prose comes from ``phrased`` (Claude); every number outside the
    prose comes from the model."""
    lang = lang if lang in _STR else "en"
    s, titles = _STR[lang], SECTION_TITLES[lang]
    esc = _html.escape
    today = _dt.date.today().isoformat()
    tiles = "".join(
        f'<div class="tile"><div class="tl">{esc(k)}</div>'
        f'<div class="tv">{esc(str(v))}</div></div>'
        for k, v in _stat_tiles(report, lang))
    sections = "".join(
        f'<section><h2>{esc(titles[k])}</h2><p>{esc(phrased["sections"][k])}</p></section>'
        for k in SECTION_KEYS)
    ad = audit or {}
    audit_line = s["audit_line"](ad.get("n_verified_relations", 0),
                                 ad.get("n_mismatched_relations", 0),
                                 ad.get("n_unverified_relations", 0))
    return f"""<!DOCTYPE html><html lang="{lang}"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(phrased['title'])}</title>
<style>
  :root {{ --paper:#f4f0e8; --ink:#201d17; --ink2:#5c564a; --ink3:#99917e;
    --gold:#a8821f; --border:#ddd4bf; }}
  body {{ margin:0; background:var(--paper); color:var(--ink);
    font:15px/1.7 Georgia,"Times New Roman",serif; }}
  .page {{ max-width:760px; margin:0 auto; padding:56px 34px 60px; }}
  .kicker {{ font:10px/1 ui-monospace,Menlo,monospace; letter-spacing:.2em;
    text-transform:uppercase; color:var(--gold); }}
  h1 {{ font-family:"Didot","Bodoni MT",Georgia,serif; font-size:30px;
    font-weight:600; margin:10px 0 6px; line-height:1.25; }}
  .meta {{ font:10.5px/1.6 ui-monospace,Menlo,monospace; letter-spacing:.08em;
    text-transform:uppercase; color:var(--ink3); margin-bottom:26px; }}
  .tiles {{ display:flex; gap:0; border-top:1px solid var(--ink);
    border-bottom:1px solid var(--border); margin:0 0 30px; }}
  .tile {{ flex:1; padding:12px 14px 14px; border-right:1px solid var(--border); }}
  .tile:last-child {{ border-right:none; }}
  .tl {{ font:9px/1.4 ui-monospace,Menlo,monospace; letter-spacing:.14em;
    text-transform:uppercase; color:var(--ink3); }}
  .tv {{ font-family:"Didot","Bodoni MT",Georgia,serif; font-size:24px;
    font-weight:600; margin-top:4px; }}
  h2 {{ font:11px/1.4 ui-monospace,Menlo,monospace; letter-spacing:.16em;
    text-transform:uppercase; color:var(--gold); margin:28px 0 8px; }}
  section p {{ margin:0; max-width:66ch; color:var(--ink2); }}
  .foot {{ margin-top:40px; border-top:1px solid var(--border);
    padding-top:12px; font:10px/1.7 ui-monospace,Menlo,monospace;
    letter-spacing:.06em; text-transform:uppercase; color:var(--ink3); }}
  @media print {{ body {{ background:#fff; }} .page {{ padding:24px 0; }} }}
</style></head><body><div class="page">
  <span class="kicker">LUMNIA · {esc(s['kicker'])}</span>
  <h1>{esc(phrased['title'])}</h1>
  <div class="meta">{esc(client_name)} · {esc(str(report.get('filename') or ''))} · {today}</div>
  {f'<div class="tiles">{tiles}</div>' if tiles else ''}
  {sections}
  <div class="foot">{esc(audit_line)}<br>{esc(s['footer'])}</div>
</div></body></html>"""
