"""The composed operations report: a client deliverable assembled from the
pipeline's computed blocks — KPI strip, plan vs actual, conversion rate,
cash split, monthly detail table.

Deterministic end to end: every figure comes from the stored model (itself
computed over the uploaded workbook), no AI anywhere, no scripts, no
external fetches — charts are hand-built inline SVG in Lumnia's design
language. A block the data cannot support is not rendered; the endpoint
declares it as skipped instead.
"""
from __future__ import annotations

import datetime as _dt
import html as _html
from typing import Any, Dict, List, Optional

# selectable blocks, in reading order
BLOCKS = ("kpi", "plan_vs_actual", "conversion", "cash", "monthly_table")

GOLD, PALE, INK3 = "#a8821f", "#d5c391", "#99917e"

_ROLES = {
    "en": {"volume": "Volume", "volume_secondary": "Output",
           "opex": "Operating costs", "capex": "CAPEX",
           "revenue": "Revenue", "budget": "Budget",
           "area": "Area", "headcount": "Headcount", "price": "Price"},
    "fr": {"volume": "Volume", "volume_secondary": "Production",
           "opex": "Charges d'exploitation", "capex": "CAPEX",
           "revenue": "Revenus", "budget": "Budget",
           "area": "Superficie", "headcount": "Effectifs", "price": "Prix"},
}

_STR = {
    "en": {
        "kicker": "Operations report",
        "title": lambda stem: f"Operations report — {stem}",
        "window": lambda a, b, n: f"{a} – {b} · {n} months",
        "of_plan_tile": lambda r: f"{r} — % of plan",
        "total_tile": lambda l: f"Total {l}",
        "pva_t": lambda r: f"Plan vs actual — {r}",
        "pva_cap": lambda pct, n, al, pl: (
            f"{pct} of plan over {n} aligned month(s) — actual “{al}” "
            f"against plan “{pl}”."),
        "conv_t": "Conversion rate by period",
        "conv_cap": lambda avg, n: f"average {avg} over {n} month(s).",
        "cash_t": "Where the tracked spend went",
        "cash_cap": lambda pct: (
            f"{pct} of the tracked spend was invested (CAPEX), the rest "
            "operated the site — counted only over months where both "
            "sides are tracked."),
        "tbl_t": "Monthly detail",
        "period": "Period", "actual": "Actual", "plan": "Plan",
        "pct": "% of plan",
        "opex_lbl": "Operating", "capex_lbl": "Invested",
        "audit_line": lambda ok, bad, un: (
            f"Audit: {ok} relation(s) verified · {bad} flagged · "
            f"{un} unverified"),
        "footer": ("Generated by Lumnia from the audited workbook — every "
                   "figure on this page traces to deterministic computation "
                   "over the uploaded data."),
    },
    "fr": {
        "kicker": "Rapport d'exploitation",
        "title": lambda stem: f"Rapport d'exploitation — {stem}",
        "window": lambda a, b, n: f"{a} – {b} · {n} mois",
        "of_plan_tile": lambda r: f"{r} — % du plan",
        "total_tile": lambda l: f"Total {l}",
        "pva_t": lambda r: f"Plan vs réel — {r}",
        "pva_cap": lambda pct, n, al, pl: (
            f"{pct} du plan sur {n} mois alignés — réel « {al} » "
            f"contre plan « {pl} »."),
        "conv_t": "Taux de conversion par période",
        "conv_cap": lambda avg, n: f"moyenne {avg} sur {n} mois.",
        "cash_t": "Où est allée la dépense suivie",
        "cash_cap": lambda pct: (
            f"{pct} de la dépense suivie a été investie (CAPEX), le reste "
            "a fait tourner le site — compté uniquement sur les mois où "
            "les deux volets sont suivis."),
        "tbl_t": "Détail mensuel",
        "period": "Période", "actual": "Réel", "plan": "Plan",
        "pct": "% du plan",
        "opex_lbl": "Exploitation", "capex_lbl": "Investi",
        "audit_line": lambda ok, bad, un: (
            f"Audit : {ok} relation(s) vérifiée(s) · {bad} signalée(s) · "
            f"{un} non vérifiée(s)"),
        "footer": ("Généré par Lumnia à partir du classeur audité — chaque "
                   "chiffre de cette page provient d'un calcul déterministe "
                   "sur les données déposées."),
    },
}


def _fmt(v: Optional[float], lang: str, dec: Optional[int] = None) -> str:
    if v is None:
        return "—"
    if dec is None:
        dec = 1 if abs(v) < 100 and v != int(v) else 0
    s = f"{v:,.{dec}f}"
    if lang == "fr":                    # 1 234,5 — narrow nbsp thousands
        s = s.replace(",", " ").replace(".", ",")
    return s


def _pct(v: Optional[float], lang: str) -> str:
    if v is None:
        return "—"
    return _fmt(v, lang, 1) + (" %" if lang == "fr" else "%")


def _monthly(report: Dict[str, Any]) -> Dict[str, Any]:
    return (report.get("model") or {}).get("monthly") or {}


def available_blocks(report: Dict[str, Any]) -> List[str]:
    """Blocks the stored model can actually support — the honest menu."""
    mo = _monthly(report)
    met = mo.get("metrics") or {}
    der = mo.get("derived") or {}
    out: List[str] = []
    if met:
        out.append("kpi")
    if mo.get("plan_vs_actual"):
        out.append("plan_vs_actual")
    if any(v is not None for v in der.get("volume_ratio") or []):
        out.append("conversion")
    if mo.get("cash"):
        out.append("cash")
    if met:
        out.append("monthly_table")
    return out


def _svg_bars(periods: List[str], series: List[tuple], lang: str,
              w: int = 640, h: int = 200) -> str:
    """Grouped bars, one group per period; series = (values, color). None
    cells simply have no bar — absence is drawn as absence."""
    ml, mr, mt, mb = 8, 8, 14, 22
    pw, ph = w - ml - mr, h - mt - mb
    mx = max((abs(v) for vals, _ in series for v in vals if v is not None),
             default=0)
    if mx == 0:
        return ""
    n = max(1, len(periods))
    group = pw / n
    bw = group * 0.72 / len(series)
    bars, labels = [], []
    for i, p in enumerate(periods):
        x0 = ml + i * group + group * 0.14
        for k, (vals, color) in enumerate(series):
            v = vals[i] if i < len(vals) else None
            if v is None:
                continue
            bh = abs(v) / mx * ph
            bars.append(
                f'<rect x="{x0 + k * bw:.1f}" y="{mt + ph - bh:.1f}" '
                f'width="{bw:.1f}" height="{bh:.1f}" fill="{color}"/>')
        labels.append(
            f'<text x="{ml + i * group + group / 2:.1f}" y="{h - 6}" '
            f'text-anchor="middle" class="ax">{_html.escape(p[:7])}</text>')
    grid = (f'<line x1="{ml}" y1="{mt + ph}" x2="{w - mr}" y2="{mt + ph}" '
            f'stroke="#ddd4bf"/>'
            f'<text x="{ml}" y="{mt - 3}" class="ax">'
            f'{_html.escape(_fmt(mx, lang))}</text>')
    return (f'<svg viewBox="0 0 {w} {h}" role="img">'
            f"{grid}{''.join(bars)}{''.join(labels)}</svg>")


def _tiles(mo: Dict[str, Any], lang: str) -> List[tuple]:
    s, roles = _STR[lang], _ROLES[lang]
    met = mo.get("metrics") or {}
    pva = mo.get("plan_vs_actual") or {}
    tiles: List[tuple] = []
    for role in ("volume", "volume_secondary", "opex"):
        m = met.get(role)
        if m:
            total = sum(v for v in m["values"] if v is not None)
            tiles.append((s["total_tile"](str(m["label"])[:26]),
                          _fmt(total, lang)))
    for role in ("volume", "volume_secondary", "opex", "capex"):
        v = pva.get(role)
        if v and v.get("pct_of_plan_total") is not None:
            tiles.append((s["of_plan_tile"](roles.get(role, role)),
                          _pct(v["pct_of_plan_total"], lang)))
    cash = mo.get("cash")
    if cash:
        tiles.append((s["capex_lbl"] + " %", _pct(cash["invested_pct"], lang)))
    return tiles[:5]


def _pva_sections(mo: Dict[str, Any], lang: str) -> str:
    s, roles = _STR[lang], _ROLES[lang]
    met = mo.get("metrics") or {}
    periods = mo.get("periods") or []
    out = []
    order = [r for r in ("volume", "volume_secondary", "opex", "capex",
                         "revenue") if r in (mo.get("plan_vs_actual") or {})]
    for role in order:
        v = mo["plan_vs_actual"][role]
        actual = (met.get(role) or {}).get("values") or []
        n_aligned = sum(1 for a, p in zip(actual, v["plan"])
                        if a is not None and p is not None)
        svg = _svg_bars(periods, [(v["plan"], PALE), (actual, GOLD)], lang)
        cap = s["pva_cap"](_pct(v["pct_of_plan_total"], lang), n_aligned,
                           str(met.get(role, {}).get("label", "")),
                           str(v["plan_label"]))
        out.append(f'<section><h2>{_html.escape(s["pva_t"](roles.get(role, role)))}</h2>'
                   f'{svg}<p class="cap">{_html.escape(cap)}</p></section>')
    return "".join(out)


def _conversion_section(mo: Dict[str, Any], lang: str) -> str:
    s = _STR[lang]
    periods = mo.get("periods") or []
    vr = (mo.get("derived") or {}).get("volume_ratio") or []
    known = [v for v in vr if v is not None]
    if not known:
        return ""
    pcts = [round(v * 100, 2) if v is not None else None for v in vr]
    avg = sum(known) / len(known) * 100
    svg = _svg_bars(periods, [(pcts, GOLD)], lang)
    cap = s["conv_cap"](_pct(round(avg, 1), lang), len(known))
    return (f'<section><h2>{_html.escape(s["conv_t"])}</h2>{svg}'
            f'<p class="cap">{_html.escape(cap)}</p></section>')


def _cash_section(mo: Dict[str, Any], lang: str) -> str:
    s = _STR[lang]
    cash = mo.get("cash")
    if not cash:
        return ""
    cap_w = cash["capex_total"] / cash["total"] * 100
    bar = (f'<svg viewBox="0 0 640 34" role="img">'
           f'<rect x="0" y="6" width="{cap_w * 6.4:.1f}" height="14" '
           f'fill="{GOLD}"/>'
           f'<rect x="{cap_w * 6.4:.1f}" y="6" '
           f'width="{(100 - cap_w) * 6.4:.1f}" height="14" fill="{PALE}"/>'
           f'<text x="0" y="32" class="ax">{_html.escape(s["capex_lbl"])} '
           f'{_html.escape(_fmt(cash["capex_total"], lang))}</text>'
           f'<text x="640" y="32" text-anchor="end" class="ax">'
           f'{_html.escape(s["opex_lbl"])} '
           f'{_html.escape(_fmt(cash["opex_total"], lang))}</text></svg>')
    cap = s["cash_cap"](_pct(cash["invested_pct"], lang))
    return (f'<section><h2>{_html.escape(s["cash_t"])}</h2>{bar}'
            f'<p class="cap">{_html.escape(cap)}</p></section>')


def _table_section(mo: Dict[str, Any], lang: str) -> str:
    s, roles = _STR[lang], _ROLES[lang]
    met = mo.get("metrics") or {}
    pva = mo.get("plan_vs_actual") or {}
    periods = mo.get("periods") or []
    order = [r for r in ("volume", "volume_secondary", "opex", "capex",
                         "revenue") if r in met]
    if not order:
        return ""
    head = "".join(f"<th>{_html.escape(p[:7])}</th>" for p in periods)
    rows = []
    for role in order:
        m = met[role]
        cells = "".join(f'<td>{_html.escape(_fmt(v, lang))}</td>'
                        for v in m["values"])
        rows.append(f'<tr><td class="rl">{_html.escape(roles.get(role, role))}'
                    f' — {_html.escape(s["actual"])}</td>{cells}</tr>')
        v = pva.get(role)
        if v:
            pcells = "".join(f'<td>{_html.escape(_fmt(p, lang))}</td>'
                             for p in v["plan"])
            rows.append(f'<tr class="mut"><td class="rl">'
                        f'{_html.escape(s["plan"])}</td>{pcells}</tr>')
            xcells = "".join(f'<td>{_html.escape(_pct(p, lang))}</td>'
                             for p in v["pct_of_plan"])
            rows.append(f'<tr class="mut"><td class="rl">'
                        f'{_html.escape(s["pct"])}</td>{xcells}</tr>')
    return (f'<section><h2>{_html.escape(s["tbl_t"])}</h2>'
            f'<table><thead><tr><th class="rl">{_html.escape(s["period"])}'
            f'</th>{head}</tr></thead><tbody>{"".join(rows)}</tbody>'
            f'</table></section>')


def render_report_html(report: Dict[str, Any], audit: Optional[Dict[str, Any]],
                       client_name: str, lang: str,
                       blocks: List[str]) -> str:
    """Typeset the composed report: pure HTML+CSS+SVG, script-free."""
    lang = lang if lang in _STR else "en"
    s = _STR[lang]
    esc = _html.escape
    mo = _monthly(report)
    periods = mo.get("periods") or []
    stem = str(report.get("filename") or "").rsplit(".", 1)[0]
    title = s["title"](stem)
    window = s["window"](periods[0][:7], periods[-1][:7], len(periods)) \
        if periods else ""
    today = _dt.date.today().isoformat()

    parts: List[str] = []
    if "kpi" in blocks:
        tiles = "".join(
            f'<div class="tile"><div class="tl">{esc(k)}</div>'
            f'<div class="tv">{esc(v)}</div></div>'
            for k, v in _tiles(mo, lang))
        if tiles:
            parts.append(f'<div class="tiles">{tiles}</div>')
    if "plan_vs_actual" in blocks:
        parts.append(_pva_sections(mo, lang))
    if "conversion" in blocks:
        parts.append(_conversion_section(mo, lang))
    if "cash" in blocks:
        parts.append(_cash_section(mo, lang))
    if "monthly_table" in blocks:
        parts.append(_table_section(mo, lang))

    ad = audit or {}
    audit_line = s["audit_line"](ad.get("n_verified_relations", 0),
                                 ad.get("n_mismatched_relations", 0),
                                 ad.get("n_unverified_relations", 0))
    return f"""<!DOCTYPE html><html lang="{lang}"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
<style>
  :root {{ --paper:#f4f0e8; --ink:#201d17; --ink2:#5c564a; --ink3:#99917e;
    --gold:#a8821f; --border:#ddd4bf; }}
  body {{ margin:0; background:var(--paper); color:var(--ink);
    font:14px/1.6 Georgia,"Times New Roman",serif; }}
  .page {{ max-width:820px; margin:0 auto; padding:52px 34px 60px; }}
  .kicker {{ font:10px/1 ui-monospace,Menlo,monospace; letter-spacing:.2em;
    text-transform:uppercase; color:var(--gold); }}
  h1 {{ font-family:"Source Serif 4","Didot","Bodoni MT",Georgia,serif;
    font-size:28px; font-weight:600; margin:10px 0 6px; line-height:1.25; }}
  .meta {{ font:10.5px/1.6 ui-monospace,Menlo,monospace; letter-spacing:.08em;
    text-transform:uppercase; color:var(--ink3); margin-bottom:26px; }}
  .tiles {{ display:flex; border-top:1px solid var(--ink);
    border-bottom:1px solid var(--border); margin:0 0 28px; }}
  .tile {{ flex:1; padding:12px 14px 14px; border-right:1px solid var(--border); }}
  .tile:last-child {{ border-right:none; }}
  .tl {{ font:9px/1.4 ui-monospace,Menlo,monospace; letter-spacing:.12em;
    text-transform:uppercase; color:var(--ink3); }}
  .tv {{ font-family:"Source Serif 4","Didot",Georgia,serif; font-size:22px;
    font-weight:600; margin-top:4px; }}
  h2 {{ font:11px/1.4 ui-monospace,Menlo,monospace; letter-spacing:.16em;
    text-transform:uppercase; color:var(--gold); margin:30px 0 10px; }}
  svg {{ display:block; width:100%; height:auto; background:#fbf9f3;
    border:1px solid var(--border); }}
  .ax {{ font:10px ui-monospace,Menlo,monospace; fill:{INK3}; }}
  .cap {{ margin:8px 0 0; font-size:12.5px; color:var(--ink2);
    max-width:76ch; }}
  table {{ border-collapse:collapse; width:100%; font-size:12.5px;
    font-variant-numeric:tabular-nums; }}
  th, td {{ text-align:right; padding:6px 8px;
    border-bottom:1px solid var(--border); }}
  th {{ font:9.5px ui-monospace,Menlo,monospace; letter-spacing:.08em;
    text-transform:uppercase; color:var(--ink3); }}
  .rl {{ text-align:left; }}
  tr.mut td {{ color:var(--ink3); }}
  .foot {{ margin-top:40px; border-top:1px solid var(--border);
    padding-top:12px; font:10px/1.7 ui-monospace,Menlo,monospace;
    letter-spacing:.06em; text-transform:uppercase; color:var(--ink3); }}
  @media print {{ body {{ background:#fff; }} .page {{ padding:24px 0; }}
    section {{ break-inside:avoid; }} }}
</style></head><body><div class="page">
  <span class="kicker">LUMNIA · {esc(s['kicker'])}</span>
  <h1>{esc(title)}</h1>
  <div class="meta">{esc(client_name)} · {esc(str(report.get('filename') or ''))} · {esc(window)} · {today}</div>
  {''.join(parts)}
  <div class="foot">{esc(audit_line)}<br>{esc(s['footer'])}</div>
</div></body></html>"""
